<?php

/**
 * @file
 * Provides hooks and helper functions for the mac_tools module.
 */

/**
 * Replaces old images folder in HTML source.
 */
function mac_tools_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {

  $from = array(
    'src="../fotos/',
    'src="fotos/',
  );
  $to = array(
    'src="/legacy/images/fotos/',
    'src="/legacy/images/fotos/',
  );
  if (isset($entity->body->value)) {
    $entity->body->value = str_replace($from, $to, $entity->body->value);
    $entity->body->format = $entity->body->format;
    $entity->body->summary = $entity->body->summary;
  }
}

/**
 * Implements hook_form_alter().
 */
function mac_tools_form_contact_message_general_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  // Removes the preview button from the form.
  $form['actions']['preview']['#access'] = FALSE;
}
