on:
  push:
    branches:
      - 'develop'
name: Tests
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Set up PHP 7.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
        tools: composer:v2
        extensions: mbstring
        coverage: none

    - name: Get composer version
      run: composer --version

    - name: Get composer cache directory
      id: composercache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache composer dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composercache.outputs.dir }}
        # Use composer.json for key, if composer.lock is not committed.
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --quiet
