on: [push, pull_request]
name: Tests and code
jobs:
#  phpunit:
#    runs-on: ubuntu-latest
#    container:
#      image: juampynr/drupal8ci:latest
#
#    services:
#      mariadb:
#        image: quay.io/juampynr/drupal8-github-actions:latest
#        ports:
#          - 33306:3306
#
#    steps:
#      - uses: actions/checkout@v1
#        with:
#          fetch-depth: 1
#
#      - name: Build project
#        run: |
#          robo job:build
#
#      - name: Run PHPUnit tests
#        run: vendor/bin/robo job:unit-tests

#  code-standards:
#    runs-on: ubuntu-latest
#    container:
#      image: juampynr/drupal8ci:latest
#
#    steps:
#      - uses: actions/checkout@v1
#        with:
#          fetch-depth: 1
#
#      - name: Build project
#        run: |
#          robo job:build
#
#      - name: Check coding standards
#        run: vendor/bin/robo job:coding-standards

#  code-coverage:
#    runs-on: ubuntu-latest
#    container:
#      image: juampynr/drupal8ci:latest
#
#    services:
#      mariadb:
#        image: quay.io/juampynr/drupal8-github-actions:latest
#        ports:
#          - 33306:3306
#
#    steps:
#      - uses: actions/checkout@v1
#        with:
#          fetch-depth: 1
#
#      - name: Build project
#        run: |
#          robo job:build
#
#      - name: Assess code coverage
#        run: |
#          vendor/bin/robo job:coverage-report
#
#      - name: Archive code coverage results
#        uses: actions/upload-artifact@v1
#        with:
#          name: coverage
#          path: coverage

#  existing-site-tests:
#    runs-on: ubuntu-latest
#    container:
#      image: juampynr/drupal8ci:latest
#
#    services:
#      mariadb:
#        image: quay.io/juampynr/drupal8-github-actions:latest
#        ports:
#          - 33306:3306
#
#    steps:
#      - uses: actions/checkout@v1
#        with:
#          fetch-depth: 1
#
#      - name: Build project
#        run: |
#          robo job:build
#
#      - name: Run existing site tests
#        run: |
#          vendor/bin/robo run:chrome-headless &
#          vendor/bin/robo job:existing-site-tests

  experimental:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: get db
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7'
          mysql database: 'default'
          mysql root password: 'root'
          mysql password: 'root'

      - name: Set up PHP 7.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          tools: composer:v2
          extensions: mbstring
          coverage: none

      - name: Get composer version
        run: composer --version

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --quiet

      - name: Copy settings
        run: cp .github/config/settings.local.php web/sites/default/settings.local.php

      - name: See status
        run: bin/drush st

      - name: Set DB
        run: |
          bin/drush sql:drop
          bin/drush sql:cli < scripts/database/dumps/drupal8.sql
          bin/drush st
          bin/drush config:get system.site

      - name: Drush deploy
        run: bin/drush deploy
